language: objective-c
osx_image: xcode10.3
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="SCrypto.xcworkspace"
  - IOS_FRAMEWORK_SCHEME="SCrypto iOS"
  - OSX_FRAMEWORK_SCHEME="SCrypto OSX"
  - IOS_SDK=iphonesimulator12.4
  - OSX_SDK=macosx10.14
  matrix:
    - DESTINATION="OS=12.4,name=iPhone 8"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD="YES" POD_LINT="YES"
    - DESTINATION="arch=x86_64"                     SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES" BUILD="YES" POD_LINT="NO"
before_install:
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - cd $TRAVIS_BUILD_DIR
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $BUILD == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test | xcpretty -c;
    fi

  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false